# Generated by Django 3.2.8 on 2021-11-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
