# Generated by Django 3.2.8 on 2021-11-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
