# Generated by Django 3.2.7 on 2021-09-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0002_answer_question_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FLOWER.user'),
        ),
    ]
