# Generated by Django 3.2.8 on 2021-11-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0003_flower_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='birth_year',
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FLOWER.question'),
        ),
        migrations.AddField(
            model_name='task',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FLOWER.flower'),
        ),
    ]
