# Generated by Django 3.2.8 on 2021-11-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0005_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='FLOWER.user'),
        ),
    ]
