# Generated by Django 3.2.7 on 2021-11-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0006_auto_20211105_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='FLOWER.user'),
        ),
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together=set(),
        ),
    ]
