# Generated by Django 3.2.7 on 2021-11-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLOWER', '0007_auto_20211105_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together={('user',)},
        ),
    ]
